# Generated by Django 3.2.8 on 2021-11-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_codes', '0002_auto_20211111_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastecodes',
            name='parent',
        ),
        migrations.AddField(
            model_name='wastecodes',
            name='code',
            field=models.CharField(default='', max_length=11, verbose_name='Код отхода'),
        ),
        migrations.AddField(
            model_name='wastecodes',
            name='parent_code',
            field=models.CharField(default='', max_length=11, verbose_name='Родительский код отхода'),
        ),
    ]
