# Generated by Django 3.2.8 on 2021-11-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_codes', '0003_auto_20211116_0539'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wastecodes',
            index=models.Index(fields=['code'], name='waste_codes_code_9d814b_idx'),
        ),
        migrations.AddIndex(
            model_name='wastecodes',
            index=models.Index(fields=['name'], name='waste_codes_name_9fedd9_idx'),
        ),
    ]
