"""empty message

Revision ID: 016291293cf8
Revises: aedc5a513212
Create Date: 2020-12-31 05:32:51.822851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016291293cf8'
down_revision = 'aedc5a513212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'queries', 'regions', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_column('queries', 'region_id')
    # ### end Alembic commands ###
