"""empty message

Revision ID: 1d8110a1b178
Revises: 7874c6765928
Create Date: 2021-07-28 12:54:47.143564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8110a1b178'
down_revision = '7874c6765928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('companies_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['companies_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_click')
    # ### end Alembic commands ###
