"""empty message

Revision ID: 20ae8c8812cc
Revises: 8f938692b4ec
Create Date: 2021-06-23 15:30:05.564230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ae8c8812cc'
down_revision = '8f938692b4ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('waste', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'waste')
    # ### end Alembic commands ###
