"""empty message

Revision ID: 2dbf32963304
Revises: 6526a658968c
Create Date: 2021-02-17 23:05:32.139074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbf32963304'
down_revision = '6526a658968c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waste_c',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itn', sa.String(length=12), nullable=True),
    sa.Column('activity', sa.String(length=600), nullable=True),
    sa.Column('fkko_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['fkko_id'], ['fkko.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste_c')
    # ### end Alembic commands ###
