"""empty message

Revision ID: 35132fb61224
Revises: 894135918c97
Create Date: 2021-01-28 22:30:49.018283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35132fb61224'
down_revision = '894135918c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('itn', sa.String(length=12), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=False),
    sa.Column('longitude', sa.String(length=20), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('regions', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'url')
    op.drop_table('companies')
    # ### end Alembic commands ###
