"""empty message

Revision ID: 3cad034d13b0
Revises: d788ac78e91e
Create Date: 2020-12-21 01:20:19.575412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cad034d13b0'
down_revision = 'd788ac78e91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('fkko_id', sa.BigInteger(), nullable=True))
    op.add_column('queries', sa.Column('locality', sa.String(length=255), nullable=True))
    op.add_column('queries', sa.Column('region', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'queries', 'fkko', ['fkko_id'], ['id'])
    op.drop_column('queries', 'address')
    op.drop_column('queries', 'fkko')
    op.add_column('users', sa.Column('position', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'position')
    op.add_column('queries', sa.Column('fkko', sa.VARCHAR(length=11), autoincrement=False, nullable=True))
    op.add_column('queries', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_column('queries', 'region')
    op.drop_column('queries', 'locality')
    op.drop_column('queries', 'fkko_id')
    # ### end Alembic commands ###
