"""empty message

Revision ID: 4064c760caff
Revises: 20ae8c8812cc
Create Date: 2021-07-13 11:10:08.416803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4064c760caff'
down_revision = '20ae8c8812cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_waste_c_itn'), 'waste_c', ['itn'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waste_c_itn'), table_name='waste_c')
    # ### end Alembic commands ###
