"""empty message

Revision ID: 5c1da3941c0e
Revises: e39f172093b6
Create Date: 2021-09-14 14:18:50.292469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1da3941c0e'
down_revision = 'e39f172093b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'description')
    # ### end Alembic commands ###
