"""empty message

Revision ID: 5ce6e3108cb2
Revises: 3cad034d13b0
Create Date: 2020-12-21 01:51:00.309536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce6e3108cb2'
down_revision = '3cad034d13b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fkkoclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fkko', sa.Column('fkkoclass_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fkko', 'fkkoclass', ['fkkoclass_id'], ['id'])
    op.drop_column('fkko', 'class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fkko', sa.Column('class', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fkko', type_='foreignkey')
    op.drop_column('fkko', 'fkkoclass_id')
    op.drop_table('fkkoclass')
    # ### end Alembic commands ###
