"""empty message

Revision ID: 5f22ede12b50
Revises: e528cbb06adf
Create Date: 2021-08-11 14:15:27.477820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f22ede12b50'
down_revision = 'e528cbb06adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('iso', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'iso')
    # ### end Alembic commands ###
