"""empty message

Revision ID: 6526a658968c
Revises: b31e1a584e17
Create Date: 2021-01-29 16:55:04.876880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6526a658968c'
down_revision = 'b31e1a584e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('activity', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'activity')
    # ### end Alembic commands ###
