"""empty message

Revision ID: 68623e8b2473
Revises: 5ce6e3108cb2
Create Date: 2020-12-24 00:30:42.546421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68623e8b2473'
down_revision = '5ce6e3108cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text')
    op.drop_table('lead')
    op.drop_table('feedback')
    op.add_column('queries', sa.Column('itn', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'itn')
    op.create_table('feedback',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mail', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_create', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ip', postgresql.INET(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pkey.public.feedback.id')
    )
    op.create_table('lead',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('contact', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contractor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mail', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('processing', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fkko', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('aggregation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('count', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('units', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('passport', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notice', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_create', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('time_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pkey.user.list.id')
    )
    op.create_table('text',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('meta', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('excerpt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('time_create', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('time_edit', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('public.text.id', sa.BIGINT(), autoincrement=False, nullable=True, comment='это ID родителя в этой же таблице'),
    sa.PrimaryKeyConstraint('id', name='pkey.public.text.id')
    )
    # ### end Alembic commands ###
