"""empty message

Revision ID: 751d65b88c2a
Revises: 1d8110a1b178
Create Date: 2021-07-28 13:12:58.736146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '751d65b88c2a'
down_revision = '1d8110a1b178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_click', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_click', sa.Column('url', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
