"""empty message

Revision ID: 7874c6765928
Revises: 7a84182a239e
Create Date: 2021-07-23 14:12:01.276591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7874c6765928'
down_revision = '7a84182a239e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fkko', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fkko', 'keywords')
    # ### end Alembic commands ###
