"""empty message

Revision ID: 7a84182a239e
Revises: 817e5d0c337b
Create Date: 2021-07-23 13:57:04.717475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a84182a239e'
down_revision = '817e5d0c337b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'checked')
    # ### end Alembic commands ###
