"""empty message

Revision ID: 817e5d0c337b
Revises: 4064c760caff
Create Date: 2021-07-13 13:49:25.310174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817e5d0c337b'
down_revision = '4064c760caff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_create', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'date_create')
    # ### end Alembic commands ###
