"""empty message

Revision ID: 894135918c97
Revises: 016291293cf8
Create Date: 2020-12-31 06:09:56.807268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894135918c97'
down_revision = '016291293cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('moderation', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'moderation')
    # ### end Alembic commands ###
