"""empty message

Revision ID: 8f938692b4ec
Revises: 2dbf32963304
Create Date: 2021-06-23 15:03:10.806395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f938692b4ec'
down_revision = '2dbf32963304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('description', sa.Text(), nullable=True))
    op.drop_constraint('queries_ibfk_4', 'queries', type_='foreignkey')
    op.drop_constraint('queries_ibfk_1', 'queries', type_='foreignkey')
    op.drop_constraint('queries_ibfk_2', 'queries', type_='foreignkey')
    op.drop_column('queries', 'date_expiry')
    op.drop_column('queries', 'count')
    op.drop_column('queries', 'unit_id')
    op.drop_column('queries', 'aggr_id')
    op.drop_column('queries', 'waste')
    op.drop_column('queries', 'locality')
    op.drop_column('queries', 'fkko_id')
    op.drop_column('users', 'middlename')
    op.drop_column('users', 'position')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'email')
    op.drop_column('users', 'itn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('itn', mysql.VARCHAR(length=12), nullable=True))
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('lastname', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('position', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('middlename', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('queries', sa.Column('fkko_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('queries', sa.Column('locality', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('queries', sa.Column('waste', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('queries', sa.Column('aggr_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('queries', sa.Column('unit_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('queries', sa.Column('count', mysql.FLOAT(), nullable=True))
    op.add_column('queries', sa.Column('date_expiry', mysql.DATETIME(), nullable=True))
    op.create_foreign_key('queries_ibfk_2', 'queries', 'fkko', ['fkko_id'], ['id'])
    op.create_foreign_key('queries_ibfk_1', 'queries', 'aggregations', ['aggr_id'], ['id'])
    op.create_foreign_key('queries_ibfk_4', 'queries', 'units', ['unit_id'], ['id'])
    op.drop_column('queries', 'description')
    # ### end Alembic commands ###
