"""empty message

Revision ID: aedc5a513212
Revises: 0da4ac1a41a1
Create Date: 2020-12-31 05:09:50.540972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aedc5a513212'
down_revision = '0da4ac1a41a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aggregations', sa.Column('text', sa.String(length=255), nullable=False))
    op.drop_column('aggregations', 'name')
    op.add_column('fkkoclass', sa.Column('text', sa.String(length=600), nullable=False))
    op.drop_column('fkkoclass', 'name')
    op.add_column('query_type', sa.Column('text', sa.String(length=20), nullable=False))
    op.drop_column('query_type', 'name')
    op.add_column('regions', sa.Column('text', sa.String(length=255), nullable=True))
    op.drop_column('regions', 'name')
    op.add_column('units', sa.Column('text', sa.String(length=10), nullable=False))
    op.drop_column('units', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('name', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('units', 'text')
    op.add_column('regions', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('regions', 'text')
    op.add_column('query_type', sa.Column('name', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('query_type', 'text')
    op.add_column('fkkoclass', sa.Column('name', mysql.VARCHAR(length=600), nullable=False))
    op.drop_column('fkkoclass', 'text')
    op.add_column('aggregations', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('aggregations', 'text')
    # ### end Alembic commands ###
