"""empty message

Revision ID: b31e1a584e17
Revises: df90eece368c
Create Date: 2021-01-29 00:16:32.033179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b31e1a584e17'
down_revision = 'df90eece368c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'latitude',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('companies', 'longitude',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'longitude',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('companies', 'latitude',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
