"""empty message

Revision ID: cbeae355d990
Revises: 35132fb61224
Create Date: 2021-01-28 23:54:37.632729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbeae355d990'
down_revision = '35132fb61224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('activity', sa.String(length=600), nullable=True))
    op.add_column('companies', sa.Column('emails', sa.String(length=600), nullable=True))
    op.add_column('companies', sa.Column('locality', sa.String(length=600), nullable=True))
    op.add_column('companies', sa.Column('phones', sa.String(length=600), nullable=True))
    op.add_column('companies', sa.Column('site', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'site')
    op.drop_column('companies', 'phones')
    op.drop_column('companies', 'locality')
    op.drop_column('companies', 'emails')
    op.drop_column('companies', 'activity')
    # ### end Alembic commands ###
