"""empty message

Revision ID: d08e9bd999e2
Revises: 68623e8b2473
Create Date: 2020-12-24 01:06:33.664046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08e9bd999e2'
down_revision = '68623e8b2473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'itn')
    op.add_column('users', sa.Column('itn', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'itn')
    op.add_column('queries', sa.Column('itn', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
