"""empty message

Revision ID: df90eece368c
Revises: cbeae355d990
Create Date: 2021-01-29 00:14:42.288786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df90eece368c'
down_revision = 'cbeae355d990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('gps', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'gps')
    # ### end Alembic commands ###
