"""empty message

Revision ID: e39f172093b6
Revises: 5f22ede12b50
Create Date: 2021-08-11 15:58:18.547818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e39f172093b6'
down_revision = '5f22ede12b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_1', 'users', 'user_type', ['type_id'], ['id'])
    # ### end Alembic commands ###
