"""empty message

Revision ID: e528cbb06adf
Revises: 7d2896de3da7
Create Date: 2021-08-09 15:49:23.028051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e528cbb06adf'
down_revision = '7d2896de3da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'user_type', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'type_id')
    op.drop_table('user_type')
    # ### end Alembic commands ###
