version: '3.4'

services:
  nginx:
    image: nginx
    container_name: uv_nginx
    volumes:
      - ./src/nginx/default.dev.conf:/etc/nginx/nginx.conf
      - ./src/:/code
    network_mode: host

volumes:
  redisdata: