# Generated by Django 3.2.8 on 2021-11-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Агрегатное состояние',
                'verbose_name_plural': 'Агрегатные состояния',
                'db_table': 'aggregations',
            },
        ),
        migrations.CreateModel(
            name='QueryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Тип заявки',
                'verbose_name_plural': 'Типы заявок',
                'db_table': 'query_types',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='WasteCodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Категория отхода',
                'verbose_name_plural': 'Категории отхода',
                'db_table': 'waste_code_category',
            },
        ),
    ]
