# Generated by Django 3.2.8 on 2021-11-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0002_aggregation_querytype_unit_wastecodecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregation',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='querytype',
            name='text',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='activity',
            field=models.CharField(max_length=600, verbose_name='С какими кодами работают в регионе'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='iso',
            field=models.CharField(max_length=10, verbose_name='Код региона'),
        ),
        migrations.AlterField(
            model_name='regions',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='text',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='wastecodecategory',
            name='text',
            field=models.CharField(max_length=600, verbose_name='Название'),
        ),
    ]
