# Generated by Django 3.2.8 on 2021-11-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0005_auto_20211115_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregation',
            name='code',
            field=models.CharField(default='00', max_length=2, verbose_name='Код агрегатного состояния'),
        ),
    ]
