# Generated by Django 3.2.8 on 2021-11-10 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dicts', '0002_aggregation_querytype_unit_wastecodecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_region', to='dicts.regions', verbose_name='Регион')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='dicts.querytype', verbose_name='Тип заявки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявка',
                'db_table': 'queries',
            },
        ),
    ]
