# Generated by Django 3.2.8 on 2021-11-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20211111_0238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companywastecodes',
            options={'verbose_name': 'Отход с которым работает компания', 'verbose_name_plural': 'Отходы с которым работают компании'},
        ),
    ]
