# Generated by Django 3.2.8 on 2021-11-16 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0006_aggregation_code'),
        ('companies', '0006_alter_companies_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_region', to='dicts.regions', verbose_name='Регион'),
        ),
    ]
