# Generated by Django 3.2.8 on 2021-11-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companies_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companywastecodes',
            name='activity',
            field=models.CharField(default='', max_length=600, verbose_name='Типы отходов с которыми работает'),
        ),
    ]
