# Generated by Django 3.2.8 on 2021-11-25 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20211125_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='actual_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время проверки актуальности'),
        ),
    ]
