# Generated by Django 3.2.8 on 2021-11-10 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0002_aggregation_querytype_unit_wastecodecategory'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_region', to='dicts.regions', verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='CompanyWasteCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='companies.companies', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Отход с которым работает компания',
                'db_table': 'company_waste_codes',
            },
        ),
    ]
