# Generated by Django 3.2.8 on 2021-11-10 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_codes', '0001_initial'),
        ('companies', '0002_auto_20211110_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='companywastecodes',
            name='waste_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_code', to='waste_codes.wastecodes', verbose_name='Код отхода'),
        ),
    ]
