# Generated by Django 3.2.8 on 2021-11-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companywastecodes_waste_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='activity',
            field=models.CharField(max_length=600, verbose_name='Типы отходов с которыми работает'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='emails',
            field=models.CharField(max_length=600, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='gps',
            field=models.CharField(max_length=255, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='itn',
            field=models.CharField(max_length=12, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='latitude',
            field=models.CharField(max_length=20, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='locality',
            field=models.CharField(max_length=600, verbose_name='Расположение?'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='longitude',
            field=models.CharField(max_length=20, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='phones',
            field=models.CharField(max_length=600, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='site',
            field=models.CharField(max_length=255, verbose_name='Сайт'),
        ),
    ]
