# Generated by Django 3.2.8 on 2021-11-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_companies_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='company_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
