# Generated by Django 3.2.8 on 2021-11-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20211117_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='company_id',
        ),
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['itn'], name='companies_itn_9d34c3_idx'),
        ),
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['name'], name='companies_name_c7a1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='companies',
            index=models.Index(fields=['region'], name='companies_region__4b2838_idx'),
        ),
        migrations.AddIndex(
            model_name='companywastecodes',
            index=models.Index(fields=['company'], name='company_was_company_c1a2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='companywastecodes',
            index=models.Index(fields=['waste_code'], name='company_was_waste_c_16d2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='companywastecodes',
            index=models.Index(fields=['activity'], name='company_was_activit_d5f25d_idx'),
        ),
    ]
