# Generated by Django 3.2.8 on 2021-11-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20211118_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
