# Generated by Django 3.2.8 on 2021-11-25 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_companies_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='checked',
        ),
        migrations.AddField(
            model_name='companies',
            name='actual',
            field=models.BooleanField(default=False, verbose_name='Актуальные данные'),
        ),
        migrations.AddField(
            model_name='companies',
            name='actual_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время проверки актуальности'),
            preserve_default=False,
        ),
    ]
