# Generated by Django 3.2.8 on 2022-01-11 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0007_regions_regions_code_aa1ecb_idx'),
        ('companies', '0014_alter_companies_actual_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='description',
            field=models.TextField(default='', verbose_name='Описание компании'),
        ),
        migrations.CreateModel(
            name='CompanySites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_sites', to='companies.companies', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Сайт компании',
                'verbose_name_plural': 'Сайты компании',
                'db_table': 'company_sites',
            },
        ),
        migrations.CreateModel(
            name='CompanyRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_region_company', to='companies.companies', verbose_name='Компания')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_region_region', to='dicts.regions', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион компании',
                'verbose_name_plural': 'Регионы компании',
                'db_table': 'company_regions',
            },
        ),
        migrations.CreateModel(
            name='CompanyPhones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_phones', to='companies.companies', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Телефон компании',
                'verbose_name_plural': 'Телефоны компании',
                'db_table': 'company_phones',
            },
        ),
        migrations.CreateModel(
            name='CompanyEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_emails', to='companies.companies', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Email компании',
                'verbose_name_plural': 'Emails компании',
                'db_table': 'company_emails',
            },
        ),
        migrations.AddIndex(
            model_name='companysites',
            index=models.Index(fields=['company'], name='company_sit_company_72be91_idx'),
        ),
        migrations.AddIndex(
            model_name='companyregion',
            index=models.Index(fields=['company'], name='company_reg_company_385e39_idx'),
        ),
        migrations.AddIndex(
            model_name='companyphones',
            index=models.Index(fields=['company'], name='company_pho_company_11c0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='companyemails',
            index=models.Index(fields=['company'], name='company_ema_company_3e0af2_idx'),
        ),
    ]
