# Generated by Django 3.2.8 on 2021-11-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='description',
            field=models.TextField(verbose_name='Описание заявки'),
        ),
        migrations.AlterField(
            model_name='queries',
            name='waste',
            field=models.CharField(max_length=255, verbose_name='Название отхода'),
        ),
    ]
