# Generated by Django 3.2.8 on 2021-11-19 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_auto_20211111_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
    ]
