# Generated by Django 3.2.8 on 2021-11-10 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dicts', '0002_aggregation_querytype_unit_wastecodecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('keywords', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('iso', models.CharField(max_length=10)),
                ('activity', models.CharField(max_length=600)),
                ('aggregation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aggregation', to='dicts.aggregation', verbose_name='Агрегатное состояние отходоа')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_code_category', to='dicts.wastecodecategory', verbose_name='Категория отходоа')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_waste_code', to='waste_codes.wastecodes', verbose_name='Родительский код отхода')),
            ],
            options={
                'verbose_name': 'Код отхода',
                'verbose_name_plural': 'Коды отхода',
                'db_table': 'waste_codes',
            },
        ),
    ]
