# Generated by Django 3.2.8 on 2021-12-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_codes', '0004_auto_20211125_0407'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wastecodes',
            index=models.Index(fields=['parent_code'], name='waste_codes_parent__f7bf61_idx'),
        ),
    ]
